language: java
jdk:
  - openjdk11

# Các lệnh để chạy trước khi thực hiện các lệnh kiểm thử
before_script:
  - echo "Starting build"

# Cấu hình thông báo
notifications:
  email:
    recipients:
      - tothanhmta@gmail.com
    on_success: change # chỉ thông báo khi trạng thái thay đổi
    on_failure: always # luôn thông báo khi có lỗi

addons:
  sonarcloud:
    organization: "tothanh93" # Thay thế bằng khóa tổ chức SonarCloud của bạn
    token:
      secure: "7b8fac6c6895d11afaa34c7b9a680011a51c9514" # Thay thế bằng token SonarCloud đã được mã hóa của bạn

# Các lệnh để chạy bộ kiểm thử và SonarCloud scan
script:
  - mvn test
  - mvn clean verify sonar:sonar -Dsonar.projectKey=your-sonarcloud-project-key # Thay thế bằng khóa dự án SonarCloud của bạn
