language: java
jdk:
  - openjdk11

# Các lệnh để chạy trước khi thực hiện các lệnh kiểm thử
before_script:
  - echo "Starting build"

# Các lệnh để chạy bộ kiểm thử
script:
  - mvn test

# Cấu hình thông báo
notifications:
  email:
    recipients:
      tothanhmta@gmail.com
    on_success: change # chỉ thông báo khi trạng thái từ thành công sang thất bại
    on_failure: always # luôn thông báo khi có lỗi
